[Service]
Environment=VIDEO_MATTING_FFMPEG=/nvme0n1-disk/code/omniserve-native/.local/ffmpeg/8.1.2/bin/ffmpeg
Environment=VIDEO_MATTING_FFPROBE=/nvme0n1-disk/code/omniserve-native/.local/ffmpeg/8.1.2/bin/ffprobe
