const char *OPENAPI_JSON =
"{\"openapi\":\"3.1.0\","
"\"info\":{\"title\":\"omniserve-native\",\"version\":\"0.4.0\","
"\"description\":\"Native C inference server: llama.cpp LLM and embeddings, stable-diffusion.cpp, and pooled multimodal/audio/3D workers behind one tier-priority scheduler.\"},"
"\"paths\":{"
"\"/health\":{\"get\":{\"summary\":\"Liveness\",\"responses\":{\"200\":{\"description\":\"ok\"}}}},"
"\"/status\":{\"get\":{\"summary\":\"VRAM, model readiness, per-tier admission counters\",\"responses\":{\"200\":{\"description\":\"status\"}}}},"
"\"/v1/models\":{\"get\":{\"summary\":\"Loaded models\",\"responses\":{\"200\":{\"description\":\"model list\"}}}},"
"\"/v1/chat/completions\":{\"post\":{\"summary\":\"OpenAI-compatible text, image, and audio chat; set stream:true for text SSE\","
"\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"type\":\"object\","
"\"required\":[\"messages\"],\"properties\":{"
"\"messages\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"role\":{\"type\":\"string\"},\"content\":{\"type\":\"string\"}}}},"
"\"max_tokens\":{\"type\":\"integer\",\"default\":512},"
"\"temperature\":{\"type\":\"number\",\"default\":0.8},"
"\"top_p\":{\"type\":\"number\",\"default\":0.92},"
"\"min_p\":{\"type\":\"number\",\"default\":0},"
"\"min_probability\":{\"type\":\"number\",\"default\":0},"
"\"enable_thinking\":{\"type\":\"boolean\",\"default\":true},"
"\"stop\":{\"oneOf\":[{\"type\":\"string\"},{\"type\":\"array\",\"items\":{\"type\":\"string\"}}]},"
"\"stream\":{\"type\":\"boolean\",\"default\":false}}}}}},"
"\"responses\":{\"200\":{\"description\":\"chat.completion or SSE chunks\"},\"401\":{\"description\":\"invalid secret\"},\"503\":{\"description\":\"no model / admission timeout\"}}}},"
"\"/v1/completions\":{\"post\":{\"summary\":\"OpenAI-compatible text completion\",\"responses\":{\"200\":{\"description\":\"text completion\"}}}},"
"\"/v1/forecasts\":{\"post\":{\"summary\":\"Chronos-2 time-series forecast through the dedicated forecast lane\","
"\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"type\":\"object\","
"\"required\":[\"values\"],\"properties\":{\"values\":{\"type\":\"array\",\"items\":{\"type\":\"number\"}},"
"\"prediction_length\":{\"type\":\"integer\",\"default\":12},"
"\"quantile_levels\":{\"type\":\"array\",\"items\":{\"type\":\"number\"}}}}}}},"
"\"responses\":{\"200\":{\"description\":\"forecast and quantiles\"},\"503\":{\"description\":\"worker missing / admission timeout\"}}}},"
"\"/v1/engines/{engine_name}/completions\":{\"post\":{\"summary\":\"Legacy OpenAI engine completion\",\"responses\":{\"200\":{\"description\":\"text completion\"}}}},"
"\"/api/v1/generate\":{\"post\":{\"summary\":\"text-generator.io-compatible generation\",\"responses\":{\"200\":{\"description\":\"generated_text results\"}}}},"
"\"/api/v1/generate-large\":{\"post\":{\"summary\":\"Large text generation compatibility alias\",\"responses\":{\"200\":{\"description\":\"generated_text results\"}}}},"
"\"/api/v1/autocomplete\":{\"post\":{\"summary\":\"Low-latency generation compatibility alias\",\"responses\":{\"200\":{\"description\":\"generated_text results\"}}}},"
"\"/api/v1/summarization\":{\"post\":{\"summary\":\"LLM summarization\",\"responses\":{\"200\":{\"description\":\"generated_text summary\"}}}},"
"\"/api/v1/feature-extraction\":{\"post\":{\"summary\":\"ModernBERT feature vector (num_features defaults to 256)\",\"responses\":{\"200\":{\"description\":\"flat embedding array\"}}}},"
"\"/v1/embeddings\":{\"post\":{\"summary\":\"OpenAI-compatible scalar or batched embeddings\",\"responses\":{\"200\":{\"description\":\"embedding list\"}}}},"
"\"/v1/images/generations\":{\"post\":{\"summary\":\"OpenAI-compatible text to image\","
"\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"type\":\"object\","
"\"required\":[\"prompt\"],\"properties\":{"
"\"prompt\":{\"type\":\"string\"},"
"\"size\":{\"type\":\"string\",\"default\":\"1024x1024\"},"
"\"width\":{\"type\":\"integer\"},\"height\":{\"type\":\"integer\"},"
"\"steps\":{\"type\":\"integer\",\"default\":9},"
"\"guidance_scale\":{\"type\":\"number\",\"default\":0},"
"\"seed\":{\"type\":\"integer\",\"default\":0},"
"\"teleport\":{\"type\":\"boolean\",\"default\":false},"
"\"teleport_start_step\":{\"type\":\"integer\",\"default\":7}}}}}},"
"\"responses\":{\"200\":{\"description\":\"OpenAI b64_json image response\"},\"503\":{\"description\":\"no model / admission timeout\"}}}},"
"\"/v1/images/segmentations\":{\"post\":{\"summary\":\"SAM2 precise object mask through the isolated scale-to-zero image-editor pool\","
"\"responses\":{\"200\":{\"description\":\"mask_url and cutout_url\"},\"503\":{\"description\":\"image editor worker not configured or unavailable\"}}}},"
"\"/v1/images/text-layers\":{\"post\":{\"summary\":\"OCR a user-drawn text box, estimate typography, and return an erase mask through the image-editor pool\","
"\"responses\":{\"200\":{\"description\":\"editable text layer and mask_url\"},\"503\":{\"description\":\"image editor worker not configured or unavailable\"}}}},"
"\"/v1/images/edits\":{\"post\":{\"summary\":\"Masked inpainting through the isolated scale-to-zero image-editor pool\","
"\"responses\":{\"200\":{\"description\":\"edited image URL\"},\"503\":{\"description\":\"image editor worker not configured or unavailable\"}}}},"
"\"/v1/images/foreground-generations/jobs\":{\"post\":{\"summary\":\"Queue text-to-image and BiRefNet matting as one foreground-art stage\","
"\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"type\":\"object\","
"\"required\":[\"prompt\"],\"properties\":{\"prompt\":{\"type\":\"string\"},"
"\"width\":{\"type\":\"integer\",\"default\":768},\"height\":{\"type\":\"integer\",\"default\":1024},"
"\"seed\":{\"type\":\"integer\",\"default\":0},\"output_format\":{\"type\":\"string\",\"default\":\"webp\"}}}}}},"
"\"responses\":{\"200\":{\"description\":\"job accepted\"}}}},"
"\"/v1/images/foreground-generations/jobs/{job_id}\":{\"get\":{\"summary\":\"Poll a foreground generation and matting job\","
"\"responses\":{\"200\":{\"description\":\"queued, generating, matting, done, or error\"},\"404\":{\"description\":\"unknown job\"}}}},"
"\"/v1/images/captions\":{\"post\":{\"summary\":\"Direct Git-base image captioning via OmniServe\",\"responses\":{\"200\":{\"description\":\"caption results\"}}}},"
"\"/v1/images/classifications\":{\"post\":{\"summary\":\"CLIP zero-shot image classification via OmniServe\",\"responses\":{\"200\":{\"description\":\"classification results\"}}}},"
"\"/v1/classifications\":{\"post\":{\"summary\":\"CLIP zero-shot text classification via OmniServe\",\"responses\":{\"200\":{\"description\":\"classification results\"}}}},"
"\"/v1/video/generations\":{\"post\":{\"summary\":\"Background-tier LTX video generation via OmniServe\",\"responses\":{\"200\":{\"description\":\"video result\"},\"507\":{\"description\":\"model does not fit current capacity\"}}}},"
"\"/loras\":{\"get\":{\"summary\":\"Installed OmniServe LoRA adapters\",\"responses\":{\"200\":{\"description\":\"LoRA catalog\"}}}},"
"\"/v1/images/backgrounds\":{\"post\":{\"summary\":\"Background scene art (Z-Image) relayed at background tier so it never preempts interactive work\","
"\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"type\":\"object\","
"\"required\":[\"prompt\"],\"properties\":{\"prompt\":{\"type\":\"string\"},"
"\"size\":{\"type\":\"string\",\"default\":\"1280x720\"},"
"\"seed\":{\"type\":\"integer\",\"default\":0}}}}}},"
"\"responses\":{\"200\":{\"description\":\"image response\"},\"503\":{\"description\":\"worker missing / admission timeout\"}}}},"
"\"/v1/images/backgrounds/style\":{\"get\":{\"summary\":\"Style-transfer an existing backdrop; same lane and background tier as the art above\","
"\"parameters\":[{\"name\":\"prompt\",\"in\":\"query\",\"required\":true,\"schema\":{\"type\":\"string\"}},"
"{\"name\":\"image_url\",\"in\":\"query\",\"required\":true,\"schema\":{\"type\":\"string\"}},"
"{\"name\":\"strength\",\"in\":\"query\",\"schema\":{\"type\":\"number\",\"default\":0.6}}],"
"\"responses\":{\"200\":{\"description\":\"image response\"},\"503\":{\"description\":\"worker missing / admission timeout\"}}}},"
"\"/v1/images/background-removals/jobs\":{\"post\":{\"summary\":\"Queue a cutout and poll for it; cache hits answer inline with the stored WebP URL\","
"\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"type\":\"object\","
"\"required\":[\"image_url\"],\"properties\":{\"image_url\":{\"type\":\"string\"},"
"\"output_format\":{\"type\":\"string\",\"default\":\"webp\"},"
"\"return_background\":{\"type\":\"boolean\",\"default\":false,"
"\"description\":\"also return the estimated backdrop, which the matte solve already computed\"},"
"\"background\":{\"type\":\"string\",\"description\":\"replacement backdrop: #rrggbb, a colour name, 'estimated', or an image URL\"},"
"\"background_prompt\":{\"type\":\"string\",\"description\":\"generate the backdrop with the diffusion lane; jobs only\"},"
"\"background_strength\":{\"type\":\"number\",\"default\":0,"
"\"description\":\"above zero, style-transfer the estimated backdrop instead of generating from scratch\"},"
"\"cache\":{\"type\":\"boolean\",\"default\":true}}}}}},"
"\"responses\":{\"200\":{\"description\":\"job accepted or cache hit\"}}}},"
"\"/v1/images/background-removals\":{\"post\":{\"summary\":\"BiRefNet transparent WebP/PNG through the C scheduler and pooled raw relay\","
"\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"type\":\"object\","
"\"required\":[\"image_url\"],\"properties\":{\"image_url\":{\"type\":\"string\"},"
"\"foreground_threshold\":{\"type\":\"number\",\"default\":0},"
"\"return_background\":{\"type\":\"boolean\",\"default\":false},"
"\"background\":{\"type\":\"string\"}}}}}},"
"\"responses\":{\"200\":{\"description\":\"transparent PNG bytes, or JSON when more than one image was asked for\"},"
"\"400\":{\"description\":\"background_prompt needs the jobs endpoint\"},"
"\"503\":{\"description\":\"worker missing / admission timeout\"}}}},"
"\"/v1/animations/generations\":{\"post\":{\"summary\":\"Idle-GPU NVIDIA ACE animation planning and R2 publication relay\","
"\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"type\":\"object\","
"\"required\":[\"prompt\",\"rig_type\",\"bones\"],\"properties\":{"
"\"prompt\":{\"type\":\"string\"},\"provider\":{\"type\":\"string\",\"default\":\"nvidia-ace\"},"
"\"rig_type\":{\"type\":\"string\",\"enum\":[\"biped\",\"quadruped\",\"arbitrary\"]},"
"\"bones\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},"
"\"publish\":{\"type\":\"object\"}}}}}},"
"\"responses\":{\"200\":{\"description\":\"animation tracks or asynchronous R2 job\"},\"503\":{\"description\":\"worker missing or background admission timeout\"}}}},"
"\"/v1/3d/generations\":{\"post\":{\"summary\":\"Idle-GPU TRELLIS.2 or Pixal3D image-to-3D relay\","
"\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"type\":\"object\","
"\"required\":[\"image_url\"],\"properties\":{"
"\"image_url\":{\"type\":\"string\",\"format\":\"uri\"},"
"\"model\":{\"type\":\"string\",\"enum\":[\"microsoft/TRELLIS.2-4B\",\"TencentARC/Pixal3D\"]},"
"\"resolution\":{\"type\":\"integer\",\"enum\":[512,1024,1536],\"default\":512},"
"\"texture_size\":{\"type\":\"integer\",\"enum\":[1024,2048,4096],\"default\":1024},"
"\"decimation_target\":{\"type\":\"integer\",\"default\":200000},"
"\"seed\":{\"type\":\"integer\"},\"publish\":{\"type\":\"object\"}}}}}},"
"\"responses\":{\"200\":{\"description\":\"GLB asset or asynchronous R2 job\"},"
"\"503\":{\"description\":\"worker missing, GPU busy, or background admission timeout\"}}}},"
"\"/v1/3d/assets/{job}/{file}\":{\"get\":{\"summary\":\"Read a locally retained generated 3D asset\","
"\"responses\":{\"200\":{\"description\":\"Generated asset bytes\"},"
"\"404\":{\"description\":\"Asset not found\"}}}},"
"\"/v1/audio/speech\":{\"post\":{\"summary\":\"OpenAI-compatible TTS relay\",\"responses\":{\"200\":{\"description\":\"audio bytes\"}}}},"
"\"/api/v1/generate_speech\":{\"post\":{\"summary\":\"text-generator.io-compatible TTS\",\"responses\":{\"200\":{\"description\":\"audio result\"}}}},"
"\"/api/v1/speech/catalog\":{\"get\":{\"summary\":\"Available TTS voices and languages\",\"responses\":{\"200\":{\"description\":\"speech catalog\"}}}},"
"\"/v1/audio/transcriptions\":{\"post\":{\"summary\":\"OpenAI-compatible STT relay\",\"responses\":{\"200\":{\"description\":\"transcription\"}}}},"
"\"/v1/training/status\":{\"get\":{\"summary\":\"Interruptible background training jobs\",\"responses\":{\"200\":{\"description\":\"job status\"}}}},"
"\"/v1/training/jobs\":{\"post\":{\"summary\":\"Queue a consent-gated ASR fine-tune\",\"responses\":{\"202\":{\"description\":\"queued\"}}}},"
"\"/v1/training/jobs/run\":{\"post\":{\"summary\":\"Run one exclusive, preemptible background segment\",\"responses\":{\"200\":{\"description\":\"completed or checkpointed\"},\"503\":{\"description\":\"waiting for VRAM\"}}}},"
"\"/api/v1/audio/transcribe\":{\"post\":{\"summary\":\"Native worker STT relay\",\"responses\":{\"200\":{\"description\":\"transcription\"}}}},"
"\"/api/v1/audio-file-extraction\":{\"post\":{\"summary\":\"Multipart audio transcription\",\"responses\":{\"200\":{\"description\":\"transcription and segments\"}}}},"
"\"/api/v1/audio-extraction\":{\"post\":{\"summary\":\"URL audio transcription\",\"responses\":{\"200\":{\"description\":\"transcription and segments\"}}}},"
"\"/api/v1/image-caption\":{\"post\":{\"summary\":\"Multipart or URL image captioning\",\"responses\":{\"200\":{\"description\":\"caption\"}}}},"
"\"/api/v1/video-question\":{\"post\":{\"summary\":\"Video question answering relay\",\"responses\":{\"200\":{\"description\":\"answer\"}}}},"
"\"/api/v1/multimodal-generate\":{\"post\":{\"summary\":\"Multimodal generation relay\",\"responses\":{\"200\":{\"description\":\"generation\"}}}},"
"\"/api/v1/voice-chat\":{\"post\":{\"summary\":\"STT to chat to TTS relay\",\"responses\":{\"200\":{\"description\":\"voice response\"}}}},"
"\"/api/v1/generate-bulk\":{\"post\":{\"summary\":\"Bulk generation relay\",\"responses\":{\"200\":{\"description\":\"results\"}}}},"
"\"/api/discord\":{\"post\":{\"summary\":\"Discord compatibility relay\",\"responses\":{\"200\":{\"description\":\"result\"}}}}},"
"\"components\":{\"securitySchemes\":{"
"\"secretHeader\":{\"type\":\"apiKey\",\"in\":\"header\",\"name\":\"secret\"},"
"\"bearer\":{\"type\":\"http\",\"scheme\":\"bearer\"}}}}";

const char *DOCS_HTML =
"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>omniserve-native API</title><style>"
"body{font:15px/1.6 system-ui,sans-serif;margin:0;background:#0b1020;color:#dce3f2}"
"main{max-width:880px;margin:0 auto;padding:40px 24px}"
"h1{font-size:28px;margin:0 0 4px}h2{font-size:19px;margin:36px 0 8px;color:#9fd0ff}"
".sub{color:#8b96ad;margin-bottom:28px}"
"code,pre{background:#141b30;border:1px solid #232d4d;border-radius:6px;color:#c7e3ff}"
"code{padding:1px 6px}pre{padding:14px;overflow-x:auto}"
".ep{display:flex;gap:10px;align-items:baseline;margin:14px 0 4px}"
".m{font-weight:700;font-size:12px;padding:2px 8px;border-radius:4px;background:#1c4a2e;color:#7fe0a7}"
".m.g{background:#1c3a5e;color:#8fc7ff}"
"a{color:#8fc7ff}</style></head><body><main>"
"<h1>omniserve-native</h1>"
"<div class='sub'>Native C inference: embedded llama.cpp text/ModernBERT embeddings and stable-diffusion.cpp, or pooled Gemma, image, 3D, multimodal, TTS and STT workers behind weighted tier-priority admission. Spec: <a href='/openapi.json'>openapi.json</a></div>"
"<h2>Auth</h2><p>Optional. When the server is started with <code>OMNISERVE_NATIVE_SECRET</code>, send it as a <code>secret</code> header or <code>Authorization: Bearer</code>. Priority via <code>X-Omniserve-Tier: paid | sub | free | background</code>.</p>"
"<h2>Chat</h2><div class='ep'><span class='m'>POST</span><code>/v1/chat/completions</code></div>"
"<pre>curl localhost:8791/v1/chat/completions -d '{\n"
"  \"messages\": [{\"role\": \"user\", \"content\": \"hello\"}],\n"
"  \"max_tokens\": 128, \"stream\": true\n}'</pre>"
"<p>Streaming uses SSE chunks in the OpenAI <code>chat.completion.chunk</code> shape, ending with <code>data: [DONE]</code>. Non-streaming returns <code>chat.completion</code> with usage, <code>cached_prompt_tokens</code>, and <code>timings.elapsed_ms</code>.</p>"
"<div class='ep'><span class='m'>POST</span><code>/v1/completions</code></div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/generate</code> — text-generator.io compatibility</div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/generate-large</code> — large-generation alias</div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/autocomplete</code> — low-latency alias</div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/summarization</code></div>"
"<h2>Embeddings</h2>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/feature-extraction</code> — flat ModernBERT vector</div>"
"<div class='ep'><span class='m'>POST</span><code>/v1/embeddings</code> — OpenAI response shape</div>"
"<h2>Images</h2><div class='ep'><span class='m'>POST</span><code>/v1/images/generations</code></div>"
"<pre>curl localhost:8791/v1/images/generations -d '{\n"
"  \"prompt\": \"a cabin in a snowstorm\", \"size\": \"768x768\", \"steps\": 9, \"seed\": 42,\n"
"  \"teleport\": true, \"teleport_start_step\": 7\n}'</pre>"
"<div class='ep'><span class='m'>POST</span><code>/v1/images/segmentations</code> — SAM2 click-based object mask via the scale-to-zero image-editor pool</div>"
"<div class='ep'><span class='m'>POST</span><code>/v1/images/text-layers</code> — OCR a text box, estimate its typography, and return an erase mask</div>"
"<div class='ep'><span class='m'>POST</span><code>/v1/images/edits</code> — regenerate only a supplied mask via the same isolated pool</div>"
"<div class='ep'><span class='m'>POST</span><code>/v1/images/backgrounds</code> — scene art via Z-Image; always background tier</div>"
"<pre>curl localhost:8791/v1/images/backgrounds -o scene.webp -d '{\n"
"  \"prompt\": \"flat vector reef background, no text\", \"size\": \"1280x720\"\n}'</pre>"
"<div class='ep'><span class='m'>GET</span><code>/v1/images/backgrounds/style</code> — restyle an existing backdrop; background tier</div>"
"<div class='ep'><span class='m'>POST</span><code>/v1/images/background-removals</code> — BiRefNet transparent WebP/PNG via pooled C relay</div>"
"<pre>curl localhost:8791/v1/images/background-removals -o cutout.png -d '{\n"
"  \"image_url\": \"https://example.com/chair.webp\"\n}'</pre>"
"<p>Ask for the backdrop the matte solve already computed, or swap it for a new one. More than one"
" image means a JSON answer instead of raw bytes.</p>"
"<pre>curl localhost:8791/v1/images/background-removals -d '{\n"
"  \"image_url\": \"https://example.com/chair.webp\",\n"
"  \"return_background\": true, \"background\": \"#ffffff\"\n}'</pre>"
"<div class='ep'><span class='m'>POST</span><code>/v1/images/background-removals/jobs</code> — queue + poll; identical inputs are answered from the WebP cache</div>"
"<p>A generated backdrop only runs here: diffusion holds a permit for its whole duration, so the"
" synchronous route refuses <code>background_prompt</code> rather than parking on an interactive slot.</p>"
"<pre>curl localhost:8791/v1/images/background-removals/jobs -d '{\n"
"  \"image_url\": \"https://example.com/chair.webp\",\n"
"  \"background_prompt\": \"a sunlit loft, no subject\"\n}'</pre>"
"<div class='ep'><span class='m'>GET</span><code>/v1/images/background-removals/jobs/{id}</code> — job status</div>"
"<div class='ep'><span class='m'>POST</span><code>/v1/images/foreground-generations/jobs</code> — text-to-image + BiRefNet in one queued stage</div>"
"<pre>curl localhost:8791/v1/images/foreground-generations/jobs -d '{\n"
"  \"prompt\": \"full-body deckhand on a plain grey backdrop\",\n"
"  \"width\": 768, \"height\": 1024, \"seed\": 42\n}'</pre>"
"<div class='ep'><span class='m'>GET</span><code>/v1/images/foreground-generations/jobs/{id}</code> — composite job status and cutout</div>"
"<h2>3D</h2><div class='ep'><span class='m'>POST</span><code>/v1/3d/generations</code> — TRELLIS.2/Pixal3D worker relay; always background tier</div>"
"<div class='ep'><span class='m'>GET</span><code>/v1/3d/assets/{job}/model.glb</code> — locally retained result</div>"
"<pre>curl localhost:8791/v1/3d/generations -d '{\n"
"  \"image_url\": \"https://example.com/object.webp\",\n"
"  \"model\": \"microsoft/TRELLIS.2-4B\", \"resolution\": 512,\n"
"  \"texture_size\": 1024, \"publish\": {\"r2\": true, \"searchable\": true}\n}'</pre>"
"<h2>Animation</h2><div class='ep'><span class='m'>POST</span><code>/v1/animations/generations</code> — NVIDIA ACE/Animation Graph worker relay; always background tier</div>"
"<pre>curl localhost:8791/v1/animations/generations -d '{\n"
"  \"prompt\": \"cautious walk and wave\", \"rig_type\": \"biped\",\n"
"  \"bones\": [\"Hips\", \"Spine\", \"Chest\"],\n"
"  \"publish\": {\"r2\": true, \"searchable\": true}\n}'</pre>"
"<h2>Audio</h2>"
"<div class='ep'><span class='m'>POST</span><code>/v1/audio/speech</code> — TTS bytes</div>"
"<div class='ep'><span class='m'>POST</span><code>/v1/audio/transcriptions</code> — multipart STT</div>"
"<div class='ep'><span class='m'>POST</span><code>/v1/training/jobs</code> — queue consent-gated ASR training</div>"
"<div class='ep'><span class='m'>POST</span><code>/v1/training/jobs/run</code> — exclusive background segment; checkpoints on serving demand</div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/generate_speech</code> — text-generator.io TTS</div>"
"<div class='ep'><span class='m g'>GET</span><code>/api/v1/speech/catalog</code> — voices and languages</div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/audio/transcribe</code> — worker STT</div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/audio-file-extraction</code> — multipart STT</div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/audio-extraction</code> — URL STT</div>"
"<h2>Multimodal</h2>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/image-caption</code></div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/video-question</code></div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/multimodal-generate</code></div>"
"<div class='ep'><span class='m'>POST</span><code>/api/v1/voice-chat</code></div>"
"<h2>Ops</h2>"
"<div class='ep'><span class='m g'>GET</span><code>/health</code></div>"
"<div class='ep'><span class='m g'>GET</span><code>/status</code> — VRAM, permits, queues, and upstream connection reuse</div>"
"<div class='ep'><span class='m g'>GET</span><code>/v1/models</code></div>"
"<h2>Run</h2>"
"<pre>OMNISERVE_NATIVE_LLM_GGUF=/models/gemma-roleplay-v2-q8_0.gguf \\\n"
"OMNISERVE_NATIVE_EMBEDDING_GGUF=/models/modernbert-base-q8_0.gguf \\\n"
"OMNISERVE_NATIVE_SD_MODEL=/models/sdxl-turbo.safetensors \\\n"
"./omniserve-native --port 8791</pre>"
"<pre>OMNISERVE_NATIVE_LLM_UPSTREAM=http://127.0.0.1:8300 \\\n"
"OMNISERVE_NATIVE_IMAGE_UPSTREAM=http://127.0.0.1:8100 \\\n"
"OMNISERVE_NATIVE_TTS_UPSTREAM=http://127.0.0.1:9083 \\\n"
"OMNISERVE_NATIVE_STT_UPSTREAM=http://127.0.0.1:9083 \\\n"
"OMNISERVE_NATIVE_SLOTS=4 ./omniserve-native --port 8791</pre>"
"<p>Front with omniserve (Python) by setting <code>OMNISERVE_PROXY_PROXY_LLM=http://127.0.0.1:8791</code> to keep its catalog, eviction, and fleet features while this server owns the hot path.</p>"
"</main></body></html>";
